site_name: OMOP MCP Server
site_description: |
  Model Context Protocol Server for the Observational Medical Outcomes Partnership (OMOP)
  Common Data Model
  A python sandbox server for the OMCP server 
site_author: Z0shua
repo_url: https://github.com/fastomop/omcp_py
repo_name: fastomop/omcp_py

theme:
  name: material
  logo: assets/omcp-logo.png
  palette:
    scheme: default
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    # - header.autohide
    - navigation.expand
    - navigation.instant
    - navigation.search.highlight
    - navigation.search.shareable
    - navigation.search.suggest
    - navigation.search.suggest.external
    - navigation.search.suggest.indexes
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.shareable
    - search.suggest
    - search.suggest.external
    - search.suggest.indexes
nav:
  - Home: index.md
  - Installation: installation.md
  - SQL:
      - Overview: sql/index.md
      - Execution: sql/execution.md
      - Validation: sql/validation.md
  - Contributing: contributing.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
plugins:
  - git-authors
  - search